pipeline:
  build:
    image: python:${PYTHON_VERSION}
    commands:
      - wget -O /usr/lib/libmfutil.so http://metwork-framework.org/pub/misc/mfutil_c/libmfutil.so
      - wget -O /usr/lib/liblayerapi2.so http://metwork-framework.org/pub/misc/mfutil_c/liblayerapi2.so
      - ldd /usr/lib/libmfutil.so
      - ldd /usr/lib/liblayerapi2.so
      - mkdir -p /opt/metwork-mfext/lib
      - pip install -r dev-requirements.txt
      - python setup.py develop
      - cd tests && rm -f test_plugins.py && nosetests -s .
      - flake8 .

matrix:
  PYTHON_VERSION:
    - 2.7-buster
    - 3.5-buster
    - 3.6-buster
    - 3.7-buster
    - 3.8-buster
