# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ test_jbv ]
  pull_request:
    branches: [ test_jbv ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dev dependencies
      run: |
        python -m pip install --upgrade pip
        wget -O libmfutil.so http://metwork-framework.org/pub/misc/mfutil_c/libmfutil.so
        wget -O liblayerapi2.so http://metwork-framework.org/pub/misc/mfutil_c/liblayerapi2.so
        pip install -r dev-requirements.txt
    - name: install
      run: |
        python setup.py develop
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --max-line-length=80 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --statistics
    - name: Tests
      uses: actions/python-nose-test
    - name: Doc
      run: |
        make doc
    - name: Publish doc 1
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PUB_HOST }}
        username: ${{ secrets.PUB_USERNAME }}
        password: ${{ secrets.PUB_PASSWORD }}
        port: 22
        script: |
          rm -Rf doc
          mkdir doc
    - name: Publish doc 2
      uses: garygrossgarten/github-action-scp@release
      with:
        local: html/mfutil
        remote: doc
        host: ${{ secrets.PUB_HOST }}
        username: ${{ secrets.PUB_USERNAME }}
        password: ${{ secrets.PUB_PASSWORD }}
    - name: Coverage
      run: |
        make coverage
    - name: Publish coverage 1
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PUB_HOST }}
        username: ${{ secrets.PUB_USERNAME }}
        password: ${{ secrets.PUB_PASSWORD }}
        port: 22
        script: |
          rm -Rf coverage
          mkdir coverage
    - name: Publish coverage 2
      uses: garygrossgarten/github-action-scp@release
      with:
        local: htmlcov
        remote: coverage
        host: ${{ secrets.PUB_HOST }}
        username: ${{ secrets.PUB_USERNAME }}
        password: ${{ secrets.PUB_PASSWORD }}
